name: 📦 Create Addon Package
on:
  workflow_call:
    inputs:
      version-name:
        required: false
        type: string
        default: ""
      release-publish:
        required: false
        type: boolean
        default: false
      latest-publish:
        required: false
        type: boolean
        default: true
    secrets:
      token:
        required: false
  workflow_dispatch:

jobs:
  create_package:
    runs-on: ubuntu-latest
    name: 📦 Build Package
    env:
      BRANCH_PREFIX: release
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1
      - uses: ./.github/actions/setvars

      - name: Setup Package
        run: ./setup-package.sh -p ${{env.ADDON_PATH}}

      # Deploy build to release/${version-name} branch
      - name: Push package to git branch ${{ env.BRANCH_PREFIX }}/${{ inputs.version-name }}
        if: ${{ inputs.release-publish }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.token }}
          branch: ${{ env.BRANCH_PREFIX }}/${{ inputs.version-name }}
          force: true

      # Deploy build to release/latest branch
      - name: Push package to git branch ${{ env.BRANCH_PREFIX }}/latest
        if: ${{ inputs.latest-publish }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.token }}
          branch: ${{ env.BRANCH_PREFIX }}/latest
          force: true
      
      # Pull lfs assets if needed
      - name: Git lfs Pull
        run: git lfs pull
        shell: bash

      # Upload package as zip
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: godot-openkcc
          retention-days: 7
          path: |
            .
            !.git

      # Restore back to original branch
      - uses: actions/checkout@v4
        if: always()
