name: 📦 Create Addon Package
on:
  workflow_call:
    inputs:
      buildArtifact:
        description: 'Should artifacts be compiled'
        required: false
        default: true
        type: boolean
  workflow_dispatch:

jobs:
  compile:
    if: ${{ github.event_name == 'workflow_dispatch' || inputs.buildArtifact }}
    uses: ./.github/workflows/gdextension_build.yml
    with:
      buildWindows: true
      buildLinux: true
      buildMacos: true
      buildAndroid: true
      buildWeb: true

  create_package:
    runs-on: "ubuntu-20.04"
    name: 📦 Build Package
    needs: compile
    if: |
      always() &&
      (needs.compile.result == 'success' || needs.compile.result == 'skipped')
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1
      - uses: ./.github/actions/setvars

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          path: extracted_files
          name: gdextension_libs

      - name: Replace with new files
        run: |
          ls -R extracted_files
          rm -rf ${{env.ADDON_LIBS_PATH}}
          mv -f extracted_files ${{env.ADDON_LIBS_PATH}}

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: godot-openkcc
          retention-days: 7
          path: ${{env.ADDON_PATH}}/*
