name: "🧪 GUT Tests"
on:
  workflow_call:
    inputs:
      buildArtifact:
        description: 'Should artifacts be compiled'
        required: false
        default: true
        type: boolean
  workflow_dispatch:

jobs:
  compile:
    if: ${{ github.event_name == 'workflow_dispatch' || inputs.buildArtifact }}
    uses: ./.github/workflows/gdextension_build.yml
    with:
      buildLinux: true
      buildWeb: true

  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    if: |
      always() &&
      (needs.compile.result == 'success' || needs.compile.result == 'skipped')
    needs: compile
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - uses: ./.github/actions/setvars
      - uses: nschloe/action-cached-lfs-checkout@v1

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          path: extracted_files
          name: gdextension_libs

      - name: Replace with new files
        run: |
          ls -R extracted_files
          find extracted_files/ -mindepth 2 -type f -exec mv -i '{}' extracted_files/ ';'
          rm -rf ${{env.ADDON_LIBS_PATH}}/
          mv -f extracted_files ${{env.ADDON_LIBS_PATH}}
          ls -R ${{env.ADDON_LIBS_PATH}}

      - name: Prepare Tests
        run: |
          godot -e --headless --path ${{env.PROJECT_PATH}} --quit-after 100 || true
          mkdir -p test_results

      - name: Run Tests
        run: |
          godot --headless --path ${{env.PROJECT_PATH}} -s res://addons/gut/gut_cmdln.gd -gjunit_xml_file=res://../test_results/results.xml -gexit

      - name: Upload Results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: test_results/results.xml
