name: "🧪 GUT Tests"
on:
  workflow_call:

jobs:
  test:
    name: 🧪 Run Tests ${{ matrix.version }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - version: "4.3"
            container: "barichello/godot-ci:4.3"
          - version: "4.2.2"
            container: "barichello/godot-ci:4.2.2"
          - version: "4.2"
            container: "barichello/godot-ci:4.2"
    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - uses: ./.github/actions/setvars
      - uses: nschloe/action-cached-lfs-checkout@v1

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          path: extracted_files
          name: gdextension_libs

      - name: Replace with new files
        run: |
          ls -R extracted_files
          find extracted_files/ -mindepth 2 -type f -exec mv -i '{}' extracted_files/ ';'
          rm -rf ${{env.ADDON_LIBS_PATH}}/
          mv -f extracted_files ${{env.ADDON_LIBS_PATH}}
          ls -R ${{env.ADDON_LIBS_PATH}}

      - name: Prepare Tests
        run: |
          godot --import --headless --path ${{env.PROJECT_PATH}} || true
          mkdir -p test_results

      - name: Run Tests
        run: |
          godot --headless --path ${{env.PROJECT_PATH}} -s res://addons/gut/gut_cmdln.gd -gjunit_xml_file=res://../test_results/results_${{ matrix.version }}.xml -gexit

      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test_results_${{ matrix.version}}
          path: test_results

  collect-results:
    needs: test
    if: success() || failure()
    name: 📦 Collect Test Results
    runs-on: ubuntu-latest

    steps:
      - name: Download Results
        uses: actions/download-artifact@v4
        with:
          pattern: test_results_*
          path: test_results
          merge-multiple: true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          retention-days: 7
          path: test_results/*
