name: "🧪 GUT Tests"
on:
  workflow_call:

jobs:
  test:
    name: 🧪 Run Tests ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 4.4.0
          - version: 4.3.0
          - version: 4.2.2
          # - version: 4.1.4

    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - uses: ./.github/actions/setvars
      - uses: nschloe/action-cached-lfs-checkout@v1

      
      - name: Setup Godot ${{ matrix.version }}
        uses: chickensoft-games/setup-godot@v2.1.1
        with:
          version: ${{ matrix.version }}
          use-dotnet: false
          include-templates: false

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          path: ${{env.ADDON_LIBS_PATH}}
          name: gdextension_libs
      
      - run: ls -R ${{env.ADDON_PATH}}
      - run: ls -R ${{env.PROJECT_PATH}}/${{env.ADDON_PATH}}

      - name: import assets
        run: godot --headless --path ${{env.PROJECT_PATH}}  --import
        continue-on-error: true

      - name: Run Tests
        run: |
          mkdir -p test_results
          godot --headless --path ${{env.PROJECT_PATH}} -s res://addons/gut/gut_cmdln.gd -gjunit_xml_file=res://../test_results/results_${{ matrix.version }}.xml -gexit

      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test_results_${{ matrix.version}}
          path: test_results

  collect-results:
    needs: test
    if: success() || failure()
    name: 📦 Collect Test Results
    runs-on: ubuntu-latest

    steps:
      - name: Download Results
        uses: actions/download-artifact@v4
        with:
          pattern: test_results_*
          path: test_results
          merge-multiple: true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          retention-days: 7
          path: test_results/*
