name: "🧪 GUT Tests"
on:
  push:
    branch:
      - main
  pull_request:
  workflow_dispatch:
  repository_dispatch:

# Environment variables for the job
env:
  SCONS_CACHE: ${{github.workspace}}/.scons-cache/
  ADDON_LIBS_PATH: openkcc/addons/openkcc/libs
  GODOT_VERSION: 4.1.1
  PROJECT_PATH: openkcc

jobs:
  compile:
    name: 🛠️ Compile Dependencies
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: 🐧 Linux
            arch: x86_64
            target: editor
            platform: linux
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Compile GDExtension for ${{matrix.name}}
        uses: ./.github/actions/compile_gdextension
        with:
          platform: ${{matrix.platform}}
          target: ${{matrix.target}}
          arch: ${{matrix.arch}}
          artifact: ${{matrix.name}}

  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    needs: compile
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          path: extracted_files

      - name: Replace with new files
        run: |
          ls -R extracted_files
          find extracted_files/ -mindepth 2 -type f -exec mv -i '{}' extracted_files/ ';'
          rm -rf ${{env.ADDON_LIBS_PATH}}/
          mv -f extracted_files ${{env.ADDON_LIBS_PATH}}
          ls -R ${{env.ADDON_LIBS_PATH}}

      - name: Prepare Tests
        run: |
          godot -e --headless --path ${{env.PROJECT_PATH}} --quit-after 100 || true
          mkdir -p test_results

      - name: Run Tests
        run: |
          godot --headless --path ${{env.PROJECT_PATH}} -s res://addons/gut/gut_cmdln.gd -gjunit_xml_file=res://../test_results/results.xml -gexit

      - name: Upload Results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: test_results/results.xml
