name: Create and Publish Package

on:
  push:
    tags:
      - '*'

jobs:
  create-release-package:
    uses: ./.github/workflows/create_package.yml
    with:
      latest-publish: false
      release-publish: true
      version-name: ${{ github.ref_name }}
