name: Create and Publish Package

on:
  push:
    tags:
      - '*'

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  id-token: write

jobs:
  compile:
    uses: ./.github/workflows/gdextension_build.yml

  create-release-package:
    uses: ./.github/workflows/create_package.yml
    needs: [ compile ]
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      latest-publish: false
      release-publish: true
      version-name: ${{ github.ref_name }}

  add-binary:
    needs: [ create-release-package ]
    runs-on: ubuntu-latest
    steps:
      # Download release package
      - name: Download Archive
        uses: actions/download-artifact@v4
        with:
          path: build
          name: godot-openkcc

      # Add binary to release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build