name: "🔃 Pull Request"

on:
  pull_request:

# Allow one PR workflow per branch
concurrency:
  group: pr-workflow-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  compile:
    uses: ./.github/workflows/gdextension_build.yml
    with:
      buildLinux: true
      buildWeb: true

  test:
    uses: ./.github/workflows/gut_tests.yml
    needs: compile

  build:
    uses: ./.github/workflows/web_build.yml
    needs: compile

  lint:
    uses: ./.github/workflows/format_validation.yml

  package-verification:
    uses: ./.github/workflows/create_package.yml
    with:
      version-name: "test"
      release-publish: false
      latest-publish: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
