name: 🌐 Web Build
on:
  workflow_call:
    inputs:
      uploadArtifact:
        description: 'Should site artifact be uploaded'
        required: false
        default: false
        type: boolean

jobs:
  build:
    name: 🌐 Build Site
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - uses: ./.github/actions/setvars
      - uses: nschloe/action-cached-lfs-checkout@v1

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          path: extracted_files
          name: gdextension_libs

      - name: Replace with new files
        run: |
          ls -R extracted_files
          mv -f extracted_files ${{env.ADDON_LIBS_PATH}}

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: 🕸 Web Build
        run: |
          run: godot -v -e --headless --path ${{env.PROJECT_PATH}} --quit || true
          mkdir ${GITHUB_WORKSPACE}/_site
          godot -v --headless --path ${{env.PROJECT_PATH}} --export-release web ${GITHUB_WORKSPACE}/_site/index.html
          cp ${{env.PROJECT_PATH}}/coi-serviceworker.min.js ${GITHUB_WORKSPACE}/_site/coi-serviceworker.min.js

      - name: Fix Permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: 📦 Upload Site Artifact
        if: ${{ inputs.uploadArtifact }}
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages