name: 🌐 Web Build
on:
  workflow_call:

jobs:
  build-game:
    name: 🌐 Build Godot Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setvars
      - uses: nschloe/action-cached-lfs-checkout@v1

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
  
      - name: Install Tools
        run: |
          dotnet tool restore
          python3 -m pip install gddoc2yml

      - name: Setup Godot ${{env.GODOT_VERSION}}
        uses: chickensoft-games/setup-godot@v2.1.1
        with:
          version: ${{env.GODOT_VERSION}}
          use-dotnet: false
          include-templates: true

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          path: ${{env.ADDON_LIBS_PATH}}
          name: gdextension_libs

      - name: import assets
        run: godot --editor --headless --path ${{env.PROJECT_PATH}} --quit-after 100 || true
        continue-on-error: true

      - name: 🕸 Web Build
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/_site
          godot -v --headless --path ${{env.PROJECT_PATH}} --export-release web ${GITHUB_WORKSPACE}/_site/index.html
          cp ${{env.PROJECT_PATH}}/coi-serviceworker.min.js ${GITHUB_WORKSPACE}/_site/coi-serviceworker.min.js

      - name: Build Docs with doctool
        run: |
          mkdir -p ${{env.PROJECT_PATH}}/doc/godot
          godot --path ${{env.PROJECT_PATH}} --doctool doc/godot --quit
          godot --path ${{env.PROJECT_PATH}} --doctool doc/classes --gdscript-docs res://scripts --quit
          godot --path ${{env.PROJECT_PATH}} --doctool doc/classes --gdscript-docs res://${{env.ADDON_PATH}}/examples --quit

      - name: Convert Docs to YML
        run: gdxml2yml --filter ${{env.PROJECT_PATH}}/doc/classes ${{env.PROJECT_PATH}}/doc/classes ${{env.PROJECT_PATH}}/doc/godot doc/api

      - name: Build site with DocFx
        run: |
          dotnet tool run docfx doc/docfx.json

      - name: Add baseUrl to xrefmap
        run: |
          sed -i '2 i baseUrl: https://openkcc.nickmaltbie.com/docs/' doc/_site/xrefmap.yml

      - name: Move docs site
        run: mv doc/_site _site/docs

      - name: Upload Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/
