name: 🌐 Web Build
on:
  workflow_call:
    inputs:
      buildArtifact:
        description: 'Should artifacts be compiled'
        required: false
        default: true
        type: boolean
      uploadArtifact:
        description: 'Should site artifact be uploaded'
        required: false
        default: false
        type: boolean

# Environment variables for the job
env:
  ADDON_LIBS_PATH: openkcc/addons/openkcc/libs
  GODOT_VERSION: 4.1.1
  PROJECT_PATH: openkcc

jobs:
  compile:
    if: ${{ github.event_name == 'workflow_dispatch' || inputs.buildArtifact }}
    uses: ./.github/workflows/gdextension_build.yml
    with:
      buildLinux: true
      buildWeb: true

  build:
    name: 🌐 Build Site
    runs-on: ubuntu-20.04
    needs: compile
    if: |
      always() &&
      (needs.compile.result == 'success' || needs.compile.result == 'skipped')
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          path: extracted_files
          name: gdextension_libs

      - name: Replace with new files
        run: |
          ls -R extracted_files
          mv -f extracted_files ${{env.ADDON_LIBS_PATH}}

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: 🕸 Web Build
        run: |
          run: godot -v -e --headless --path ${{env.PROJECT_PATH}} --quit || true
          mkdir ${GITHUB_WORKSPACE}/_site
          godot -v --headless --path ${{env.PROJECT_PATH}} --export-release web ${GITHUB_WORKSPACE}/_site/index.html
          cp ${{env.PROJECT_PATH}}/coi-serviceworker.min.js ${GITHUB_WORKSPACE}/_site/coi-serviceworker.min.js

      - name: Fix Permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: 📦 Upload Site Artifact
        if: ${{ inputs.uploadArtifact }}
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages