name: 🌐 Web Build
on:
  workflow_call:

jobs:
  build-game:
    name: 🌐 Build Godot Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setvars
      - uses: nschloe/action-cached-lfs-checkout@v1

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
  
      - name: Install Tools
        run: |
          dotnet tool restore
          python3 -m pip install gddoc2yml

      - name: Setup Godot ${{env.GODOT_VERSION}}
        uses: chickensoft-games/setup-godot@v2.1.1
        with:
          version: ${{env.GODOT_VERSION}}
          use-dotnet: false
          include-templates: true

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          path: ${{env.ADDON_LIBS_PATH}}
          name: gdextension_libs

      - name: import assets
        run: godot --headless --path ${{env.PROJECT_PATH}} --import
        continue-on-error: true

      - name: 🕸 Web Build
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/_site
          godot -v --headless --path ${{env.PROJECT_PATH}} --export-release web ${GITHUB_WORKSPACE}/_site/index.html
          cp ${{env.PROJECT_PATH}}/coi-serviceworker.min.js ${GITHUB_WORKSPACE}/_site/coi-serviceworker.min.js

      - name: Build Docs with doctool
        run: |
          mkdir -p doc/tmp/godot
          godot --path ${{env.PROJECT_PATH}} --doctool ../doc/tmp/godot

      - name: Build yml Docs for API
        run: |
          gdxml2yml --filter doc/xml/scripts doc/xml/doc_classes \
              --path doc/xml/scripts doc/xml/example doc/xml/doc_classes doc/tmp/godot \
              --output doc/gen/api

      - name: Build yml Docs for Example
        run: |
          gdxml2yml --filter doc/xml/example \
              --path doc/xml/scripts doc/xml/example doc/xml/doc_classes doc/tmp/godot \
              --output doc/gen/example

      - name: Build site with DocFx
        run: |
          dotnet tool run docfx doc/docfx.json

      - name: Add baseUrl to xrefmap
        run: |
          sed -i '2 i baseUrl: https://openkcc.nickmaltbie.com/docs/' doc/_site/xrefmap.yml

      - name: Move docs site
        run: mv doc/_site _site/docs

      - name: Upload Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/
